(** Palette module type and runtime utilities for color palettes.

    Provides the signature that all generated palette modules must implement,
    plus helper functions for building custom palettes with efficient
    nearest-color lookup. *)

(** Signature for palette modules generated by the [%palette] PPX extension. *)
module type M = sig
  (** Palette color type (typically a variant of color names). *)
  type t

  (** Convert a color name string to the palette type.
      @raise InvalidColorName if the name is not in the palette *)
  val of_string : string -> t

  (** Get the ANSI color code for a palette color. *)
  val to_code : t -> int

  (** Convert a palette color to its RGB representation. *)
  val to_color : t -> Gg.v4

  (** List of all colors in the palette (in order). *)
  val color_list : Gg.v4 list

  (** Find the nearest palette color to the given color using perceptual distance
      (LAB color space). *)
  val nearest : Gg.v4 -> Gg.v4
end

(** Exception raised when an invalid color name is provided to [of_string]. *)
exception InvalidColorName of string

(** Opaque type for nearest-neighbor search index.

    Contains an octree in LAB color space and a reverse lookup map from
    LAB coordinates to original RGBA colors. *)
type nearest_index

(** Build a nearest-neighbor index from a list of colors.

    The index uses LAB color space for perceptual distance calculations.
    @param leaf_size Optional octree leaf size (default determined by oktree)
    @param color_list List of RGBA colors to index *)
val nearest_index_of_color_list : ?leaf_size:int -> Gg.v4 list -> nearest_index

(** Query the nearest color using a prebuilt index.
    @param index Prebuilt nearest-neighbor index
    @param target Target color to match *)
val nearest_with_index : nearest_index -> Gg.v4 -> Gg.v4

(** Create a reusable nearest-color lookup function for a color list.

    Builds the index once and returns a function that can be called multiple times.
    @param leaf_size Optional octree leaf size
    @param color_list List of colors to create palette from
    @return Function that finds nearest color in the palette *)
val nearest_of_list : ?leaf_size:int -> Gg.v4 list -> (Gg.v4 -> Gg.v4)

(** Convert an RGBA color to LAB 3D coordinates (for testing/debugging).
    Alpha channel is ignored. *)
val lab3_of_color : Gg.v4 -> Gg.V3.t
